targets:
  $default:
    builders:
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/shared/api/client/*.dart
            - lib/shared/api/providers/*.dart
            - lib/shared/api/sse/*.dart
            - lib/shared/auth/*.dart
            - lib/facilitator/session/*.dart
            - lib/facilitator/features/**/*.dart
          exclude:
            - lib/shared/api/gen/**
