run-admin:
	flutter run --dart-define-from-file=env/dev.json -t lib/main_admin.dart --flavor admin

run-facilitator:
	flutter run --dart-define-from-file=env/dev.json -t lib/main_facilitator.dart --flavor facilitator