// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type AdminSession struct {
	ID               string             `json:"id"`
	AdminID          string             `json:"admin_id"`
	AccessTokenHash  string             `json:"access_token_hash"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceInfo       string             `json:"device_info"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type AuditLog struct {
	ID         string             `json:"id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	Target     string             `json:"target"`
	Success    bool               `json:"success"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Metadata   []byte             `json:"metadata"`
}

type Badge struct {
	ID              string      `json:"id"`
	ShortID         string      `json:"short_id"`
	QrPayload       string      `json:"qr_payload"`
	Status          string      `json:"status"`
	AssignedGroupID pgtype.Text `json:"assigned_group_id"`
}

type BroadcastReceipt struct {
	MessageID string             `json:"message_id"`
	TrackID   string             `json:"track_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type Camp struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	StartAt              pgtype.Timestamptz `json:"start_at"`
	EndAt                pgtype.Timestamptz `json:"end_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	EndedAt              pgtype.Timestamptz `json:"ended_at"`
	Status               string             `json:"status"`
	BottleneckMinSamples int32              `json:"bottleneck_min_samples"`
	BottleneckRatioPct   int32              `json:"bottleneck_ratio_pct"`
}

type Corner struct {
	ID            string `json:"id"`
	CampID        string `json:"camp_id"`
	Name          string `json:"name"`
	TargetMinutes int32  `json:"target_minutes"`
	IsMandatory   bool   `json:"is_mandatory"`
}

type DeviceRegistration struct {
	ID                string             `json:"id"`
	CampID            string             `json:"camp_id"`
	DeviceName        string             `json:"device_name"`
	Status            string             `json:"status"`
	TokenHash         string             `json:"token_hash"`
	FailedPinAttempts int32              `json:"failed_pin_attempts"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
}

type FacilitatorSession struct {
	ID        string             `json:"id"`
	TrackID   string             `json:"track_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Group struct {
	ID        string `json:"id"`
	CampID    string `json:"camp_id"`
	Name      string `json:"name"`
	BadgeID   string `json:"badge_id"`
	Itinerary []byte `json:"itinerary"`
}

type Message struct {
	ID          string             `json:"id"`
	ChannelType string             `json:"channel_type"`
	TrackID     pgtype.Text        `json:"track_id"`
	SenderRole  string             `json:"sender_role"`
	Content     string             `json:"content"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
}

type Track struct {
	ID             string             `json:"id"`
	CornerID       string             `json:"corner_id"`
	TrackNo        int32              `json:"track_no"`
	Status         string             `json:"status"`
	PinHash        string             `json:"pin_hash"`
	CurrentVisitID pgtype.Text        `json:"current_visit_id"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Visit struct {
	ID          string             `json:"id"`
	GroupID     string             `json:"group_id"`
	CornerID    string             `json:"corner_id"`
	TrackID     string             `json:"track_id"`
	Status      string             `json:"status"`
	InputMethod string             `json:"input_method"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}
