// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 시스템 관리자 계정을 관리하는 테이블
type Admin struct {
	// 관리자 고유 식별자
	ID string `json:"id"`
	// 관리자 로그인 아이디
	Username string `json:"username"`
	// 비밀번호 해시
	PasswordHash string `json:"password_hash"`
}

// 관리자의 인증 토큰(Access/Refresh) 세션을 관리하는 테이블
type AdminSession struct {
	// 세션 고유 식별자
	ID string `json:"id"`
	// 관리자 식별자
	AdminID string `json:"admin_id"`
	// Access Token 해시
	AccessTokenHash string `json:"access_token_hash"`
	// Refresh Token 해시
	RefreshTokenHash string `json:"refresh_token_hash"`
	// 로그인 환경(User-Agent 등) 정보
	DeviceInfo string `json:"device_info"`
	// 세션 생성 시간
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 마지막 세션 사용 시간 (슬라이딩 만료용)
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	// 세션이 무효화된 시간
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Announcement struct {
	ID         string             `json:"id"`
	CampID     string             `json:"camp_id"`
	SenderRole string             `json:"sender_role"`
	Content    string             `json:"content"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
}

// 각 트랙의 공지 읽음 상태를 저장하는 테이블
type AnnouncementReceipt struct {
	AnnouncementID string             `json:"announcement_id"`
	TrackID        string             `json:"track_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

// 보안 이벤트 및 주요 시스템 변경 이력을 기록하는 감사(Audit) 로그 테이블
type AuditLog struct {
	// 감사 로그 고유 식별자
	ID string `json:"id"`
	// 행위자 (관리자 ID, 진행자 ID 등)
	Actor string `json:"actor"`
	// 수행한 동작 (예: APPROVED_DEVICE, FAILED_PIN 등)
	Action string `json:"action"`
	// 동작의 대상 (기기 ID, 트랙 ID 등)
	Target string `json:"target"`
	// 동작 성공 여부
	Success bool `json:"success"`
	// 이벤트 발생 시간
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	// 이벤트와 관련된 추가 정보 (JSON)
	Metadata []byte `json:"metadata"`
}

// 물리적 QR 배지 정보를 관리하는 테이블
type Badge struct {
	// 배지 고유 식별자
	ID string `json:"id"`
	// 인쇄용/사용자 식별용 짧은 ID
	ShortID string `json:"short_id"`
	// QR 코드에 인코딩된 실제 페이로드 문자열
	QrPayload string `json:"qr_payload"`
	// 배지 상태 (UNASSIGNED, ASSIGNED 등)
	Status string `json:"status"`
	// 배지가 할당된 조 식별자
	AssignedGroupID pgtype.Text `json:"assigned_group_id"`
}

// 캠프(행사) 전체의 기본 정보 및 병목 판단 기준을 관리하는 테이블
type Camp struct {
	// 캠프 고유 식별자
	ID string `json:"id"`
	// 캠프 이름
	Name string `json:"name"`
	// 캠프 예정 시작 시간
	StartAt pgtype.Timestamptz `json:"start_at"`
	// 캠프 예정 종료 시간
	EndAt pgtype.Timestamptz `json:"end_at"`
	// 실제 캠프가 활성화된 시간
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	// 실제 캠프가 종료된 시간
	EndedAt pgtype.Timestamptz `json:"ended_at"`
	// 캠프 상태 (PENDING, ACTIVE, ENDED 등)
	Status string `json:"status"`
	// 병목 판단을 위한 최소 방문 기록 샘플 수
	BottleneckMinSamples int32 `json:"bottleneck_min_samples"`
	// 목표 시간 대비 지연 비율(%) 임계값
	BottleneckRatioPct int32 `json:"bottleneck_ratio_pct"`
}

// 캠프 내의 각 코너(부스/프로그램)를 정의하는 테이블
type Corner struct {
	// 코너 고유 식별자
	ID string `json:"id"`
	// 소속 캠프 식별자
	CampID string `json:"camp_id"`
	// 코너 이름
	Name string `json:"name"`
	// 코너별 목표 진행 시간(분)
	TargetMinutes int32 `json:"target_minutes"`
	// 필수 코너 여부
	IsMandatory bool `json:"is_mandatory"`
}

// 진행자 기기의 등록 요청 및 승인/잠금 상태를 관리하는 테이블
type DeviceRegistration struct {
	// 기기 등록 요청 고유 식별자
	ID string `json:"id"`
	// 요청된 캠프 식별자
	CampID string `json:"camp_id"`
	// 기기 식별을 위한 기기명 (사용자 입력)
	DeviceName string `json:"device_name"`
	// 등록 상태 (PENDING, APPROVED, REJECTED, REVOKED)
	Status string `json:"status"`
	// 기기를 인증하기 위한 토큰 해시
	TokenHash string `json:"token_hash"`
	// 트랙 PIN 입력 실패 횟수
	FailedPinAttempts int32 `json:"failed_pin_attempts"`
	// PIN 오입력으로 인한 잠금 해제 예정 시간
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	// 관리자에 의해 승인된 시간
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	// 기기 등록 요청이 생성된 시각
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 특정 트랙에 로그인한 진행자의 세션 상태를 관리하는 테이블
type FacilitatorSession struct {
	// 세션 고유 식별자
	ID string `json:"id"`
	// 로그인한 트랙 식별자
	TrackID string `json:"track_id"`
	// 세션 인증 토큰 해시
	TokenHash string `json:"token_hash"`
	// 세션 생성 시간
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 세션이 무효화(로그아웃/강제종료)된 시간
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// 캠프에 참가하여 코너를 순회하는 단위인 조(그룹) 테이블
type Group struct {
	// 조 고유 식별자
	ID string `json:"id"`
	// 소속 캠프 식별자
	CampID string `json:"camp_id"`
	// 조 이름
	Name string `json:"name"`
	// 할당된 배지 식별자
	BadgeID string `json:"badge_id"`
	// 조의 코너 순회표 (방문해야 할 코너와 상태 목록 JSON)
	Itinerary []byte `json:"itinerary"`
}

// 트랙별 운영자/진행자 스레드 메시지를 저장하는 테이블
type Message struct {
	// 메시지 고유 식별자
	ID string `json:"id"`
	// 메시지 스레드의 트랙 식별자
	TrackID string `json:"track_id"`
	// 발신자 역할 (ADMIN 등)
	SenderRole string `json:"sender_role"`
	// 메시지 본문
	Content string `json:"content"`
	// 발송 시간
	SentAt pgtype.Timestamptz `json:"sent_at"`
	ReadAt pgtype.Timestamptz `json:"read_at"`
}

// 코너 내에서 병렬로 진행 가능한 세부 트랙(기기/테이블)을 정의하는 테이블
type Track struct {
	// 트랙 고유 식별자
	ID string `json:"id"`
	// 소속 코너 식별자
	CornerID string `json:"corner_id"`
	// 코너 내 트랙 번호 (1, 2, 3...)
	TrackNo int32 `json:"track_no"`
	// 트랙 상태 (ACTIVE, DELETED 등)
	Status string `json:"status"`
	// 기기 등록을 위한 PIN 해시값
	PinHash string `json:"pin_hash"`
	// PIN 재인쇄 전용 AES-256-GCM 암호문
	PinCiphertext pgtype.Text `json:"pin_ciphertext"`
	// 현재 진행 중인 방문(Visit)의 식별자
	CurrentVisitID pgtype.Text `json:"current_visit_id"`
	// 논리적 삭제 시간
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	UnreadByAdminCount int32              `json:"unread_by_admin_count"`
	UnreadByTrackCount int32              `json:"unread_by_track_count"`
}

// 조가 코너(트랙)를 방문하여 진행한 이력을 저장하는 테이블
type Visit struct {
	// 방문 고유 식별자
	ID string `json:"id"`
	// 방문한 조 식별자
	GroupID string `json:"group_id"`
	// 방문한 코너 식별자
	CornerID string `json:"corner_id"`
	// 방문한 트랙 식별자
	TrackID string `json:"track_id"`
	// 방문 상태 (IN_PROGRESS, COMPLETED 등)
	Status string `json:"status"`
	// 입력 방식 (QR_SCAN, MANUAL 등)
	InputMethod string `json:"input_method"`
	// 방문 시작 시간
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// 방문 종료 시간
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}
