// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminsByRole = `-- name: CountAdminsByRole :one
SELECT COUNT(*) FROM admins WHERE role = $1
`

func (q *Queries) CountAdminsByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminsByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const deleteCorner = `-- name: DeleteCorner :exec
DELETE FROM corners WHERE id = $1
`

func (q *Queries) DeleteCorner(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCorner, id)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, password_hash, role FROM admins WHERE id = $1
`

func (q *Queries) GetAdmin(ctx context.Context, id string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role FROM admins WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT id, admin_id, access_token_hash, device_info, created_at, last_used_at, revoked_at FROM admin_sessions WHERE id = $1
`

func (q *Queries) GetAdminSession(ctx context.Context, id string) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSession, id)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.AccessTokenHash,
		&i.DeviceInfo,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminSessionByAccessTokenHash = `-- name: GetAdminSessionByAccessTokenHash :one
SELECT id, admin_id, access_token_hash, device_info, created_at, last_used_at, revoked_at FROM admin_sessions WHERE access_token_hash = $1
`

func (q *Queries) GetAdminSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByAccessTokenHash, accessTokenHash)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.AccessTokenHash,
		&i.DeviceInfo,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAnnouncementReceiptByAnnouncementAndTrack = `-- name: GetAnnouncementReceiptByAnnouncementAndTrack :one
SELECT announcement_id, track_id, read_at FROM announcement_receipts WHERE announcement_id = $1 AND track_id = $2
`

type GetAnnouncementReceiptByAnnouncementAndTrackParams struct {
	AnnouncementID string `json:"announcement_id"`
	TrackID        string `json:"track_id"`
}

func (q *Queries) GetAnnouncementReceiptByAnnouncementAndTrack(ctx context.Context, arg GetAnnouncementReceiptByAnnouncementAndTrackParams) (AnnouncementReceipt, error) {
	row := q.db.QueryRow(ctx, getAnnouncementReceiptByAnnouncementAndTrack, arg.AnnouncementID, arg.TrackID)
	var i AnnouncementReceipt
	err := row.Scan(&i.AnnouncementID, &i.TrackID, &i.ReadAt)
	return i, err
}

const getBadge = `-- name: GetBadge :one
SELECT id, short_id, qr_payload, status, assigned_group_id FROM badges WHERE id = $1
`

func (q *Queries) GetBadge(ctx context.Context, id string) (Badge, error) {
	row := q.db.QueryRow(ctx, getBadge, id)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.QrPayload,
		&i.Status,
		&i.AssignedGroupID,
	)
	return i, err
}

const getBadgeByQRPayload = `-- name: GetBadgeByQRPayload :one
SELECT id, short_id, qr_payload, status, assigned_group_id FROM badges WHERE qr_payload = $1
`

func (q *Queries) GetBadgeByQRPayload(ctx context.Context, qrPayload string) (Badge, error) {
	row := q.db.QueryRow(ctx, getBadgeByQRPayload, qrPayload)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.QrPayload,
		&i.Status,
		&i.AssignedGroupID,
	)
	return i, err
}

const getCamp = `-- name: GetCamp :one
SELECT id, name, start_at, end_at, activated_at, ended_at, status, bottleneck_min_samples, bottleneck_ratio_pct FROM camps WHERE id = $1
`

func (q *Queries) GetCamp(ctx context.Context, id string) (Camp, error) {
	row := q.db.QueryRow(ctx, getCamp, id)
	var i Camp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartAt,
		&i.EndAt,
		&i.ActivatedAt,
		&i.EndedAt,
		&i.Status,
		&i.BottleneckMinSamples,
		&i.BottleneckRatioPct,
	)
	return i, err
}

const getCompletedVisitByGroupAndCorner = `-- name: GetCompletedVisitByGroupAndCorner :one
SELECT id, group_id, corner_id, track_id, status, input_method, started_at, ended_at FROM visits WHERE group_id = $1 AND corner_id = $2 AND status = 'COMPLETED' ORDER BY ended_at DESC LIMIT 1
`

type GetCompletedVisitByGroupAndCornerParams struct {
	GroupID  string `json:"group_id"`
	CornerID string `json:"corner_id"`
}

func (q *Queries) GetCompletedVisitByGroupAndCorner(ctx context.Context, arg GetCompletedVisitByGroupAndCornerParams) (Visit, error) {
	row := q.db.QueryRow(ctx, getCompletedVisitByGroupAndCorner, arg.GroupID, arg.CornerID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CornerID,
		&i.TrackID,
		&i.Status,
		&i.InputMethod,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getCorner = `-- name: GetCorner :one
SELECT id, camp_id, name, target_minutes, is_mandatory FROM corners WHERE id = $1
`

func (q *Queries) GetCorner(ctx context.Context, id string) (Corner, error) {
	row := q.db.QueryRow(ctx, getCorner, id)
	var i Corner
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.Name,
		&i.TargetMinutes,
		&i.IsMandatory,
	)
	return i, err
}

const getCornerView = `-- name: GetCornerView :one
SELECT
    c.id,
    c.name,
    c.target_minutes,
    c.camp_id,
    metrics.sample_count,
    metrics.avg_duration_seconds,
    active_tracks.active_tracks
FROM corners c
JOIN LATERAL (
    SELECT
        COUNT(*)::BIGINT AS sample_count,
        COALESCE(AVG(EXTRACT(EPOCH FROM (v.ended_at - v.started_at))), 0)::DOUBLE PRECISION AS avg_duration_seconds
    FROM visits v
    WHERE v.corner_id = c.id AND v.status = 'COMPLETED'
) metrics ON TRUE
JOIN LATERAL (
    SELECT COALESCE(
        jsonb_agg(jsonb_build_object(
            'id', t.id,
            'cornerId', t.corner_id,
            'trackNo', t.track_no,
            'status', t.status,
            'operationalStatus', CASE WHEN t.current_visit_id IS NULL THEN 'IDLE' ELSE 'BUSY' END
        ) ORDER BY t.track_no),
        '[]'::jsonb
    ) AS active_tracks
    FROM tracks t
    WHERE t.corner_id = c.id AND t.status = 'ACTIVE'
) active_tracks ON TRUE
WHERE c.id = $1
`

type GetCornerViewRow struct {
	ID                 string      `json:"id"`
	Name               string      `json:"name"`
	TargetMinutes      int32       `json:"target_minutes"`
	CampID             string      `json:"camp_id"`
	SampleCount        int64       `json:"sample_count"`
	AvgDurationSeconds float64     `json:"avg_duration_seconds"`
	ActiveTracks       interface{} `json:"active_tracks"`
}

func (q *Queries) GetCornerView(ctx context.Context, id string) (GetCornerViewRow, error) {
	row := q.db.QueryRow(ctx, getCornerView, id)
	var i GetCornerViewRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetMinutes,
		&i.CampID,
		&i.SampleCount,
		&i.AvgDurationSeconds,
		&i.ActiveTracks,
	)
	return i, err
}

const getDeviceRegistration = `-- name: GetDeviceRegistration :one
SELECT id, camp_id, device_name, status, token_hash, failed_pin_attempts, locked_until, approved_at, created_at FROM device_registrations WHERE id = $1
`

func (q *Queries) GetDeviceRegistration(ctx context.Context, id string) (DeviceRegistration, error) {
	row := q.db.QueryRow(ctx, getDeviceRegistration, id)
	var i DeviceRegistration
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.DeviceName,
		&i.Status,
		&i.TokenHash,
		&i.FailedPinAttempts,
		&i.LockedUntil,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceRegistrationByTokenHash = `-- name: GetDeviceRegistrationByTokenHash :one
SELECT id, camp_id, device_name, status, token_hash, failed_pin_attempts, locked_until, approved_at, created_at FROM device_registrations WHERE token_hash = $1
`

func (q *Queries) GetDeviceRegistrationByTokenHash(ctx context.Context, tokenHash string) (DeviceRegistration, error) {
	row := q.db.QueryRow(ctx, getDeviceRegistrationByTokenHash, tokenHash)
	var i DeviceRegistration
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.DeviceName,
		&i.Status,
		&i.TokenHash,
		&i.FailedPinAttempts,
		&i.LockedUntil,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFacilitatorSession = `-- name: GetFacilitatorSession :one
SELECT id, track_id, token_hash, created_at, revoked_at FROM facilitator_sessions WHERE id = $1
`

func (q *Queries) GetFacilitatorSession(ctx context.Context, id string) (FacilitatorSession, error) {
	row := q.db.QueryRow(ctx, getFacilitatorSession, id)
	var i FacilitatorSession
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getFacilitatorSessionByTokenHash = `-- name: GetFacilitatorSessionByTokenHash :one
SELECT id, track_id, token_hash, created_at, revoked_at FROM facilitator_sessions WHERE token_hash = $1
`

func (q *Queries) GetFacilitatorSessionByTokenHash(ctx context.Context, tokenHash string) (FacilitatorSession, error) {
	row := q.db.QueryRow(ctx, getFacilitatorSessionByTokenHash, tokenHash)
	var i FacilitatorSession
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, camp_id, name, badge_id, itinerary FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.Name,
		&i.BadgeID,
		&i.Itinerary,
	)
	return i, err
}

const getGroupByBadge = `-- name: GetGroupByBadge :one
SELECT id, camp_id, name, badge_id, itinerary FROM groups WHERE camp_id = $1 AND badge_id = $2
`

type GetGroupByBadgeParams struct {
	CampID  string `json:"camp_id"`
	BadgeID string `json:"badge_id"`
}

func (q *Queries) GetGroupByBadge(ctx context.Context, arg GetGroupByBadgeParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByBadge, arg.CampID, arg.BadgeID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CampID,
		&i.Name,
		&i.BadgeID,
		&i.Itinerary,
	)
	return i, err
}

const getInProgressVisitByTrack = `-- name: GetInProgressVisitByTrack :one
SELECT id, group_id, corner_id, track_id, status, input_method, started_at, ended_at FROM visits WHERE track_id = $1 AND status = 'IN_PROGRESS'
`

func (q *Queries) GetInProgressVisitByTrack(ctx context.Context, trackID string) (Visit, error) {
	row := q.db.QueryRow(ctx, getInProgressVisitByTrack, trackID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CornerID,
		&i.TrackID,
		&i.Status,
		&i.InputMethod,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, corner_id, track_no, status, pin_hash, pin_ciphertext, current_visit_id, deleted_at, unread_by_admin_count, unread_by_track_count FROM tracks WHERE id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.CornerID,
		&i.TrackNo,
		&i.Status,
		&i.PinHash,
		&i.PinCiphertext,
		&i.CurrentVisitID,
		&i.DeletedAt,
		&i.UnreadByAdminCount,
		&i.UnreadByTrackCount,
	)
	return i, err
}

const getVisit = `-- name: GetVisit :one
SELECT id, group_id, corner_id, track_id, status, input_method, started_at, ended_at FROM visits WHERE id = $1
`

func (q *Queries) GetVisit(ctx context.Context, id string) (Visit, error) {
	row := q.db.QueryRow(ctx, getVisit, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CornerID,
		&i.TrackID,
		&i.Status,
		&i.InputMethod,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const incrementTrackUnreadCount = `-- name: IncrementTrackUnreadCount :exec
UPDATE tracks
SET unread_by_admin_count = unread_by_admin_count + CASE WHEN $1::VARCHAR = 'ADMIN' THEN 1 ELSE 0 END,
    unread_by_track_count = unread_by_track_count + CASE WHEN $1::VARCHAR = 'TRACK' THEN 1 ELSE 0 END
WHERE id = $2
`

type IncrementTrackUnreadCountParams struct {
	Recipient string `json:"recipient"`
	TrackID   string `json:"track_id"`
}

func (q *Queries) IncrementTrackUnreadCount(ctx context.Context, arg IncrementTrackUnreadCountParams) error {
	_, err := q.db.Exec(ctx, incrementTrackUnreadCount, arg.Recipient, arg.TrackID)
	return err
}

const listActiveFacilitatorSessionsByCamp = `-- name: ListActiveFacilitatorSessionsByCamp :many
SELECT f.id, f.track_id, f.token_hash, f.created_at, f.revoked_at FROM facilitator_sessions f
JOIN tracks t ON f.track_id = t.id
JOIN corners c ON t.corner_id = c.id
WHERE c.camp_id = $1 AND f.revoked_at IS NULL
`

func (q *Queries) ListActiveFacilitatorSessionsByCamp(ctx context.Context, campID string) ([]FacilitatorSession, error) {
	rows, err := q.db.Query(ctx, listActiveFacilitatorSessionsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacilitatorSession
	for rows.Next() {
		var i FacilitatorSession
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveFacilitatorSessionsByTrack = `-- name: ListActiveFacilitatorSessionsByTrack :many
SELECT id, track_id, token_hash, created_at, revoked_at FROM facilitator_sessions WHERE track_id = $1 AND revoked_at IS NULL
`

func (q *Queries) ListActiveFacilitatorSessionsByTrack(ctx context.Context, trackID string) ([]FacilitatorSession, error) {
	rows, err := q.db.Query(ctx, listActiveFacilitatorSessionsByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacilitatorSession
	for rows.Next() {
		var i FacilitatorSession
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTracksByCamp = `-- name: ListActiveTracksByCamp :many
SELECT t.id, t.corner_id, t.track_no, t.status, t.pin_hash, t.pin_ciphertext, t.current_visit_id, t.deleted_at, t.unread_by_admin_count, t.unread_by_track_count FROM tracks t
JOIN corners c ON t.corner_id = c.id
WHERE c.camp_id = $1 AND t.status = 'ACTIVE'
`

func (q *Queries) ListActiveTracksByCamp(ctx context.Context, campID string) ([]Track, error) {
	rows, err := q.db.Query(ctx, listActiveTracksByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.CornerID,
			&i.TrackNo,
			&i.Status,
			&i.PinHash,
			&i.PinCiphertext,
			&i.CurrentVisitID,
			&i.DeletedAt,
			&i.UnreadByAdminCount,
			&i.UnreadByTrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSessionsByAdmin = `-- name: ListAdminSessionsByAdmin :many
SELECT id, admin_id, access_token_hash, device_info, created_at, last_used_at, revoked_at FROM admin_sessions
WHERE admin_id = $1 AND revoked_at IS NULL
`

func (q *Queries) ListAdminSessionsByAdmin(ctx context.Context, adminID string) ([]AdminSession, error) {
	rows, err := q.db.Query(ctx, listAdminSessionsByAdmin, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSession
	for rows.Next() {
		var i AdminSession
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.AccessTokenHash,
			&i.DeviceInfo,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBadges = `-- name: ListAllBadges :many
SELECT id, short_id, qr_payload, status, assigned_group_id FROM badges
`

func (q *Queries) ListAllBadges(ctx context.Context) ([]Badge, error) {
	rows, err := q.db.Query(ctx, listAllBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.QrPayload,
			&i.Status,
			&i.AssignedGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementReceiptsByAnnouncement = `-- name: ListAnnouncementReceiptsByAnnouncement :many
SELECT announcement_id, track_id, read_at FROM announcement_receipts WHERE announcement_id = $1
`

func (q *Queries) ListAnnouncementReceiptsByAnnouncement(ctx context.Context, announcementID string) ([]AnnouncementReceipt, error) {
	rows, err := q.db.Query(ctx, listAnnouncementReceiptsByAnnouncement, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnnouncementReceipt
	for rows.Next() {
		var i AnnouncementReceipt
		if err := rows.Scan(&i.AnnouncementID, &i.TrackID, &i.ReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementsByCamp = `-- name: ListAnnouncementsByCamp :many
SELECT id, camp_id, sender_role, content, sent_at FROM announcements WHERE camp_id = $1 ORDER BY sent_at
`

func (q *Queries) ListAnnouncementsByCamp(ctx context.Context, campID string) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.SenderRole,
			&i.Content,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor, action, target, success, occurred_at, metadata FROM audit_logs
WHERE ($1::VARCHAR IS NULL OR actor ILIKE '%' || $1::VARCHAR || '%')
  AND ($2::VARCHAR IS NULL OR action = $2::VARCHAR)
  AND ($3::BOOLEAN IS NULL OR success = $3::BOOLEAN)
  AND (
    $4::TIMESTAMPTZ IS NULL
    OR (occurred_at, id) < ($4::TIMESTAMPTZ, $5::VARCHAR)
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $6
`

type ListAuditLogsParams struct {
	Actor            pgtype.Text        `json:"actor"`
	Action           pgtype.Text        `json:"action"`
	Success          pgtype.Bool        `json:"success"`
	BeforeOccurredAt pgtype.Timestamptz `json:"before_occurred_at"`
	BeforeID         pgtype.Text        `json:"before_id"`
	PageLimit        int32              `json:"page_limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Actor,
		arg.Action,
		arg.Success,
		arg.BeforeOccurredAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Success,
			&i.OccurredAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCamps = `-- name: ListCamps :many
SELECT id, name, start_at, end_at, activated_at, ended_at, status, bottleneck_min_samples, bottleneck_ratio_pct FROM camps
`

func (q *Queries) ListCamps(ctx context.Context) ([]Camp, error) {
	rows, err := q.db.Query(ctx, listCamps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Camp
	for rows.Next() {
		var i Camp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartAt,
			&i.EndAt,
			&i.ActivatedAt,
			&i.EndedAt,
			&i.Status,
			&i.BottleneckMinSamples,
			&i.BottleneckRatioPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCornerViewsByCamp = `-- name: ListCornerViewsByCamp :many
SELECT
    c.id,
    c.name,
    c.camp_id,
    c.target_minutes,
    metrics.sample_count,
    metrics.avg_duration_seconds,
    active_tracks.active_tracks
FROM corners c
JOIN LATERAL (
    SELECT
        COUNT(*)::BIGINT AS sample_count,
        COALESCE(AVG(EXTRACT(EPOCH FROM (v.ended_at - v.started_at))), 0)::DOUBLE PRECISION AS avg_duration_seconds
    FROM visits v
    WHERE v.corner_id = c.id AND v.status = 'COMPLETED'
) metrics ON TRUE
JOIN LATERAL (
    SELECT COALESCE(
        jsonb_agg(jsonb_build_object(
            'id', t.id,
            'cornerId', t.corner_id,
            'trackNo', t.track_no,
            'status', t.status,
            'operationalStatus', CASE WHEN t.current_visit_id IS NULL THEN 'IDLE' ELSE 'BUSY' END
        ) ORDER BY t.track_no),
        '[]'::jsonb
    ) AS active_tracks
    FROM tracks t
    WHERE t.corner_id = c.id AND t.status = 'ACTIVE'
) active_tracks ON TRUE
WHERE c.camp_id = $1
ORDER BY c.id
`

type ListCornerViewsByCampRow struct {
	ID                 string      `json:"id"`
	Name               string      `json:"name"`
	CampID             string      `json:"camp_id"`
	TargetMinutes      int32       `json:"target_minutes"`
	SampleCount        int64       `json:"sample_count"`
	AvgDurationSeconds float64     `json:"avg_duration_seconds"`
	ActiveTracks       interface{} `json:"active_tracks"`
}

func (q *Queries) ListCornerViewsByCamp(ctx context.Context, campID string) ([]ListCornerViewsByCampRow, error) {
	rows, err := q.db.Query(ctx, listCornerViewsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCornerViewsByCampRow
	for rows.Next() {
		var i ListCornerViewsByCampRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CampID,
			&i.TargetMinutes,
			&i.SampleCount,
			&i.AvgDurationSeconds,
			&i.ActiveTracks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCornersByCamp = `-- name: ListCornersByCamp :many
SELECT id, camp_id, name, target_minutes, is_mandatory FROM corners WHERE camp_id = $1
`

func (q *Queries) ListCornersByCamp(ctx context.Context, campID string) ([]Corner, error) {
	rows, err := q.db.Query(ctx, listCornersByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Corner
	for rows.Next() {
		var i Corner
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.Name,
			&i.TargetMinutes,
			&i.IsMandatory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceRegistrationsByCampAndStatus = `-- name: ListDeviceRegistrationsByCampAndStatus :many
SELECT id, camp_id, device_name, status, token_hash, failed_pin_attempts, locked_until, approved_at, created_at FROM device_registrations
WHERE camp_id = $1 AND ($2::VARCHAR IS NULL OR status = $2)
`

type ListDeviceRegistrationsByCampAndStatusParams struct {
	CampID string      `json:"camp_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) ListDeviceRegistrationsByCampAndStatus(ctx context.Context, arg ListDeviceRegistrationsByCampAndStatusParams) ([]DeviceRegistration, error) {
	rows, err := q.db.Query(ctx, listDeviceRegistrationsByCampAndStatus, arg.CampID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceRegistration
	for rows.Next() {
		var i DeviceRegistration
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.DeviceName,
			&i.Status,
			&i.TokenHash,
			&i.FailedPinAttempts,
			&i.LockedUntil,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByCamp = `-- name: ListGroupsByCamp :many
SELECT id, camp_id, name, badge_id, itinerary FROM groups WHERE camp_id = $1
`

func (q *Queries) ListGroupsByCamp(ctx context.Context, campID string) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.Name,
			&i.BadgeID,
			&i.Itinerary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByTrack = `-- name: ListMessagesByTrack :many
SELECT id, track_id, sender_role, content, sent_at, read_at FROM messages WHERE track_id = $1 ORDER BY sent_at
`

func (q *Queries) ListMessagesByTrack(ctx context.Context, trackID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.SenderRole,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByTrackAfter = `-- name: ListMessagesByTrackAfter :many
SELECT id, track_id, sender_role, content, sent_at, read_at FROM messages
WHERE track_id = $1
  AND ($2::TIMESTAMPTZ IS NULL OR sent_at > $2::TIMESTAMPTZ)
ORDER BY sent_at
`

type ListMessagesByTrackAfterParams struct {
	TrackID string             `json:"track_id"`
	After   pgtype.Timestamptz `json:"after"`
}

func (q *Queries) ListMessagesByTrackAfter(ctx context.Context, arg ListMessagesByTrackAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByTrackAfter, arg.TrackID, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.SenderRole,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeviceRegistrationsByCamp = `-- name: ListPendingDeviceRegistrationsByCamp :many
SELECT id, camp_id, device_name, status, token_hash, failed_pin_attempts, locked_until, approved_at, created_at FROM device_registrations WHERE camp_id = $1 AND status = 'PENDING'
`

func (q *Queries) ListPendingDeviceRegistrationsByCamp(ctx context.Context, campID string) ([]DeviceRegistration, error) {
	rows, err := q.db.Query(ctx, listPendingDeviceRegistrationsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceRegistration
	for rows.Next() {
		var i DeviceRegistration
		if err := rows.Scan(
			&i.ID,
			&i.CampID,
			&i.DeviceName,
			&i.Status,
			&i.TokenHash,
			&i.FailedPinAttempts,
			&i.LockedUntil,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByCamp = `-- name: ListTracksByCamp :many
SELECT t.id, t.corner_id, t.track_no, t.status, t.pin_hash, t.pin_ciphertext, t.current_visit_id, t.deleted_at, t.unread_by_admin_count, t.unread_by_track_count FROM tracks t
JOIN corners c ON t.corner_id = c.id
WHERE c.camp_id = $1
`

func (q *Queries) ListTracksByCamp(ctx context.Context, campID string) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.CornerID,
			&i.TrackNo,
			&i.Status,
			&i.PinHash,
			&i.PinCiphertext,
			&i.CurrentVisitID,
			&i.DeletedAt,
			&i.UnreadByAdminCount,
			&i.UnreadByTrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByCorner = `-- name: ListTracksByCorner :many
SELECT id, corner_id, track_no, status, pin_hash, pin_ciphertext, current_visit_id, deleted_at, unread_by_admin_count, unread_by_track_count FROM tracks WHERE corner_id = $1
`

func (q *Queries) ListTracksByCorner(ctx context.Context, cornerID string) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByCorner, cornerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.CornerID,
			&i.TrackNo,
			&i.Status,
			&i.PinHash,
			&i.PinCiphertext,
			&i.CurrentVisitID,
			&i.DeletedAt,
			&i.UnreadByAdminCount,
			&i.UnreadByTrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsByCamp = `-- name: ListVisitsByCamp :many
SELECT v.id, v.group_id, v.corner_id, v.track_id, v.status, v.input_method, v.started_at, v.ended_at, c.target_minutes, c.name as corner_name FROM visits v
JOIN groups g ON v.group_id = g.id
JOIN corners c ON v.corner_id = c.id
WHERE g.camp_id = $1
`

type ListVisitsByCampRow struct {
	ID            string             `json:"id"`
	GroupID       string             `json:"group_id"`
	CornerID      string             `json:"corner_id"`
	TrackID       string             `json:"track_id"`
	Status        string             `json:"status"`
	InputMethod   string             `json:"input_method"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	TargetMinutes int32              `json:"target_minutes"`
	CornerName    string             `json:"corner_name"`
}

func (q *Queries) ListVisitsByCamp(ctx context.Context, campID string) ([]ListVisitsByCampRow, error) {
	rows, err := q.db.Query(ctx, listVisitsByCamp, campID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitsByCampRow
	for rows.Next() {
		var i ListVisitsByCampRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CornerID,
			&i.TrackID,
			&i.Status,
			&i.InputMethod,
			&i.StartedAt,
			&i.EndedAt,
			&i.TargetMinutes,
			&i.CornerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsByGroup = `-- name: ListVisitsByGroup :many
SELECT id, group_id, corner_id, track_id, status, input_method, started_at, ended_at FROM visits WHERE group_id = $1 ORDER BY started_at ASC
`

func (q *Queries) ListVisitsByGroup(ctx context.Context, groupID string) ([]Visit, error) {
	rows, err := q.db.Query(ctx, listVisitsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visit
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CornerID,
			&i.TrackID,
			&i.Status,
			&i.InputMethod,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllMessagesReadByRecipient = `-- name: MarkAllMessagesReadByRecipient :exec
UPDATE messages
SET read_at = COALESCE(read_at, $1::TIMESTAMPTZ)
WHERE track_id = $2
  AND sender_role <> $3::VARCHAR
  AND read_at IS NULL
`

type MarkAllMessagesReadByRecipientParams struct {
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	TrackID   string             `json:"track_id"`
	Recipient string             `json:"recipient"`
}

func (q *Queries) MarkAllMessagesReadByRecipient(ctx context.Context, arg MarkAllMessagesReadByRecipientParams) error {
	_, err := q.db.Exec(ctx, markAllMessagesReadByRecipient, arg.ReadAt, arg.TrackID, arg.Recipient)
	return err
}

const resetTrackUnreadCount = `-- name: ResetTrackUnreadCount :exec
UPDATE tracks
SET unread_by_admin_count = CASE WHEN $1::VARCHAR = 'ADMIN' THEN 0 ELSE unread_by_admin_count END,
    unread_by_track_count = CASE WHEN $1::VARCHAR = 'TRACK' THEN 0 ELSE unread_by_track_count END
WHERE id = $2
`

type ResetTrackUnreadCountParams struct {
	Reader  string `json:"reader"`
	TrackID string `json:"track_id"`
}

func (q *Queries) ResetTrackUnreadCount(ctx context.Context, arg ResetTrackUnreadCountParams) error {
	_, err := q.db.Exec(ctx, resetTrackUnreadCount, arg.Reader, arg.TrackID)
	return err
}

const saveAdmin = `-- name: SaveAdmin :exec
INSERT INTO admins (id, username, password_hash, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role
`

type SaveAdminParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) SaveAdmin(ctx context.Context, arg SaveAdminParams) error {
	_, err := q.db.Exec(ctx, saveAdmin,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
	)
	return err
}

const saveAdminSession = `-- name: SaveAdminSession :exec
INSERT INTO admin_sessions (id, admin_id, access_token_hash, device_info, created_at, last_used_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    last_used_at = EXCLUDED.last_used_at,
    revoked_at = EXCLUDED.revoked_at
`

type SaveAdminSessionParams struct {
	ID              string             `json:"id"`
	AdminID         string             `json:"admin_id"`
	AccessTokenHash string             `json:"access_token_hash"`
	DeviceInfo      string             `json:"device_info"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) SaveAdminSession(ctx context.Context, arg SaveAdminSessionParams) error {
	_, err := q.db.Exec(ctx, saveAdminSession,
		arg.ID,
		arg.AdminID,
		arg.AccessTokenHash,
		arg.DeviceInfo,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	return err
}

const saveAnnouncement = `-- name: SaveAnnouncement :exec
INSERT INTO announcements (id, camp_id, sender_role, content, sent_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveAnnouncementParams struct {
	ID         string             `json:"id"`
	CampID     string             `json:"camp_id"`
	SenderRole string             `json:"sender_role"`
	Content    string             `json:"content"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) SaveAnnouncement(ctx context.Context, arg SaveAnnouncementParams) error {
	_, err := q.db.Exec(ctx, saveAnnouncement,
		arg.ID,
		arg.CampID,
		arg.SenderRole,
		arg.Content,
		arg.SentAt,
	)
	return err
}

const saveAnnouncementReceipt = `-- name: SaveAnnouncementReceipt :exec
INSERT INTO announcement_receipts (announcement_id, track_id, read_at)
VALUES ($1, $2, $3)
ON CONFLICT (announcement_id, track_id) DO UPDATE SET
    read_at = EXCLUDED.read_at
`

type SaveAnnouncementReceiptParams struct {
	AnnouncementID string             `json:"announcement_id"`
	TrackID        string             `json:"track_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) SaveAnnouncementReceipt(ctx context.Context, arg SaveAnnouncementReceiptParams) error {
	_, err := q.db.Exec(ctx, saveAnnouncementReceipt, arg.AnnouncementID, arg.TrackID, arg.ReadAt)
	return err
}

const saveAuditLog = `-- name: SaveAuditLog :exec
INSERT INTO audit_logs (id, actor, action, target, success, occurred_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveAuditLogParams struct {
	ID         string             `json:"id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	Target     string             `json:"target"`
	Success    bool               `json:"success"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) SaveAuditLog(ctx context.Context, arg SaveAuditLogParams) error {
	_, err := q.db.Exec(ctx, saveAuditLog,
		arg.ID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Success,
		arg.OccurredAt,
		arg.Metadata,
	)
	return err
}

const saveBadge = `-- name: SaveBadge :exec
INSERT INTO badges (id, short_id, qr_payload, status, assigned_group_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    assigned_group_id = EXCLUDED.assigned_group_id
`

type SaveBadgeParams struct {
	ID              string      `json:"id"`
	ShortID         string      `json:"short_id"`
	QrPayload       string      `json:"qr_payload"`
	Status          string      `json:"status"`
	AssignedGroupID pgtype.Text `json:"assigned_group_id"`
}

func (q *Queries) SaveBadge(ctx context.Context, arg SaveBadgeParams) error {
	_, err := q.db.Exec(ctx, saveBadge,
		arg.ID,
		arg.ShortID,
		arg.QrPayload,
		arg.Status,
		arg.AssignedGroupID,
	)
	return err
}

const saveCamp = `-- name: SaveCamp :exec
INSERT INTO camps (id, name, start_at, end_at, activated_at, ended_at, status, bottleneck_min_samples, bottleneck_ratio_pct)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    activated_at = EXCLUDED.activated_at,
    ended_at = EXCLUDED.ended_at,
    status = EXCLUDED.status,
    bottleneck_min_samples = EXCLUDED.bottleneck_min_samples,
    bottleneck_ratio_pct = EXCLUDED.bottleneck_ratio_pct
`

type SaveCampParams struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	StartAt              pgtype.Timestamptz `json:"start_at"`
	EndAt                pgtype.Timestamptz `json:"end_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	EndedAt              pgtype.Timestamptz `json:"ended_at"`
	Status               string             `json:"status"`
	BottleneckMinSamples int32              `json:"bottleneck_min_samples"`
	BottleneckRatioPct   int32              `json:"bottleneck_ratio_pct"`
}

func (q *Queries) SaveCamp(ctx context.Context, arg SaveCampParams) error {
	_, err := q.db.Exec(ctx, saveCamp,
		arg.ID,
		arg.Name,
		arg.StartAt,
		arg.EndAt,
		arg.ActivatedAt,
		arg.EndedAt,
		arg.Status,
		arg.BottleneckMinSamples,
		arg.BottleneckRatioPct,
	)
	return err
}

const saveCorner = `-- name: SaveCorner :exec
INSERT INTO corners (id, camp_id, name, target_minutes, is_mandatory)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    target_minutes = EXCLUDED.target_minutes,
    is_mandatory = EXCLUDED.is_mandatory
`

type SaveCornerParams struct {
	ID            string `json:"id"`
	CampID        string `json:"camp_id"`
	Name          string `json:"name"`
	TargetMinutes int32  `json:"target_minutes"`
	IsMandatory   bool   `json:"is_mandatory"`
}

func (q *Queries) SaveCorner(ctx context.Context, arg SaveCornerParams) error {
	_, err := q.db.Exec(ctx, saveCorner,
		arg.ID,
		arg.CampID,
		arg.Name,
		arg.TargetMinutes,
		arg.IsMandatory,
	)
	return err
}

const saveDeviceRegistration = `-- name: SaveDeviceRegistration :exec
INSERT INTO device_registrations (id, camp_id, device_name, status, token_hash, failed_pin_attempts, locked_until, approved_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    failed_pin_attempts = EXCLUDED.failed_pin_attempts,
    locked_until = EXCLUDED.locked_until,
    approved_at = EXCLUDED.approved_at
`

type SaveDeviceRegistrationParams struct {
	ID                string             `json:"id"`
	CampID            string             `json:"camp_id"`
	DeviceName        string             `json:"device_name"`
	Status            string             `json:"status"`
	TokenHash         string             `json:"token_hash"`
	FailedPinAttempts int32              `json:"failed_pin_attempts"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveDeviceRegistration(ctx context.Context, arg SaveDeviceRegistrationParams) error {
	_, err := q.db.Exec(ctx, saveDeviceRegistration,
		arg.ID,
		arg.CampID,
		arg.DeviceName,
		arg.Status,
		arg.TokenHash,
		arg.FailedPinAttempts,
		arg.LockedUntil,
		arg.ApprovedAt,
		arg.CreatedAt,
	)
	return err
}

const saveFacilitatorSession = `-- name: SaveFacilitatorSession :exec
INSERT INTO facilitator_sessions (id, track_id, token_hash, created_at, revoked_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    revoked_at = EXCLUDED.revoked_at
`

type SaveFacilitatorSessionParams struct {
	ID        string             `json:"id"`
	TrackID   string             `json:"track_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) SaveFacilitatorSession(ctx context.Context, arg SaveFacilitatorSessionParams) error {
	_, err := q.db.Exec(ctx, saveFacilitatorSession,
		arg.ID,
		arg.TrackID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const saveGroup = `-- name: SaveGroup :exec
INSERT INTO groups (id, camp_id, name, badge_id, itinerary)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    badge_id = EXCLUDED.badge_id,
    itinerary = EXCLUDED.itinerary
`

type SaveGroupParams struct {
	ID        string `json:"id"`
	CampID    string `json:"camp_id"`
	Name      string `json:"name"`
	BadgeID   string `json:"badge_id"`
	Itinerary []byte `json:"itinerary"`
}

func (q *Queries) SaveGroup(ctx context.Context, arg SaveGroupParams) error {
	_, err := q.db.Exec(ctx, saveGroup,
		arg.ID,
		arg.CampID,
		arg.Name,
		arg.BadgeID,
		arg.Itinerary,
	)
	return err
}

const saveMessage = `-- name: SaveMessage :exec
INSERT INTO messages (id, track_id, sender_role, content, sent_at, read_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveMessageParams struct {
	ID         string             `json:"id"`
	TrackID    string             `json:"track_id"`
	SenderRole string             `json:"sender_role"`
	Content    string             `json:"content"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) error {
	_, err := q.db.Exec(ctx, saveMessage,
		arg.ID,
		arg.TrackID,
		arg.SenderRole,
		arg.Content,
		arg.SentAt,
		arg.ReadAt,
	)
	return err
}

const saveTrack = `-- name: SaveTrack :exec
INSERT INTO tracks (id, corner_id, track_no, status, pin_hash, pin_ciphertext, current_visit_id, deleted_at, unread_by_admin_count, unread_by_track_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    pin_hash = EXCLUDED.pin_hash,
    pin_ciphertext = EXCLUDED.pin_ciphertext,
    current_visit_id = EXCLUDED.current_visit_id,
    deleted_at = EXCLUDED.deleted_at,
    unread_by_admin_count = EXCLUDED.unread_by_admin_count,
    unread_by_track_count = EXCLUDED.unread_by_track_count
`

type SaveTrackParams struct {
	ID                 string             `json:"id"`
	CornerID           string             `json:"corner_id"`
	TrackNo            int32              `json:"track_no"`
	Status             string             `json:"status"`
	PinHash            string             `json:"pin_hash"`
	PinCiphertext      pgtype.Text        `json:"pin_ciphertext"`
	CurrentVisitID     pgtype.Text        `json:"current_visit_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	UnreadByAdminCount int32              `json:"unread_by_admin_count"`
	UnreadByTrackCount int32              `json:"unread_by_track_count"`
}

func (q *Queries) SaveTrack(ctx context.Context, arg SaveTrackParams) error {
	_, err := q.db.Exec(ctx, saveTrack,
		arg.ID,
		arg.CornerID,
		arg.TrackNo,
		arg.Status,
		arg.PinHash,
		arg.PinCiphertext,
		arg.CurrentVisitID,
		arg.DeletedAt,
		arg.UnreadByAdminCount,
		arg.UnreadByTrackCount,
	)
	return err
}

const saveVisit = `-- name: SaveVisit :exec
INSERT INTO visits (id, group_id, corner_id, track_id, status, input_method, started_at, ended_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    ended_at = EXCLUDED.ended_at
`

type SaveVisitParams struct {
	ID          string             `json:"id"`
	GroupID     string             `json:"group_id"`
	CornerID    string             `json:"corner_id"`
	TrackID     string             `json:"track_id"`
	Status      string             `json:"status"`
	InputMethod string             `json:"input_method"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) SaveVisit(ctx context.Context, arg SaveVisitParams) error {
	_, err := q.db.Exec(ctx, saveVisit,
		arg.ID,
		arg.GroupID,
		arg.CornerID,
		arg.TrackID,
		arg.Status,
		arg.InputMethod,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}
