// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteCorner(ctx context.Context, id string) error
	GetAdmin(ctx context.Context, id string) (Admin, error)
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetAdminSession(ctx context.Context, id string) (AdminSession, error)
	GetAdminSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) (AdminSession, error)
	GetAdminSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AdminSession, error)
	GetBadge(ctx context.Context, id string) (Badge, error)
	GetBadgeByQRPayload(ctx context.Context, qrPayload string) (Badge, error)
	GetBroadcastReceiptByMessageAndTrack(ctx context.Context, arg GetBroadcastReceiptByMessageAndTrackParams) (BroadcastReceipt, error)
	GetCamp(ctx context.Context, id string) (Camp, error)
	GetCompletedVisitByGroupAndCorner(ctx context.Context, arg GetCompletedVisitByGroupAndCornerParams) (Visit, error)
	GetCorner(ctx context.Context, id string) (Corner, error)
	GetDeviceRegistration(ctx context.Context, id string) (DeviceRegistration, error)
	GetDeviceRegistrationByTokenHash(ctx context.Context, tokenHash string) (DeviceRegistration, error)
	GetFacilitatorSession(ctx context.Context, id string) (FacilitatorSession, error)
	GetFacilitatorSessionByTokenHash(ctx context.Context, tokenHash string) (FacilitatorSession, error)
	GetGroup(ctx context.Context, id string) (Group, error)
	GetGroupByBadge(ctx context.Context, arg GetGroupByBadgeParams) (Group, error)
	GetInProgressVisitByTrack(ctx context.Context, trackID string) (Visit, error)
	GetTrack(ctx context.Context, id string) (Track, error)
	GetVisit(ctx context.Context, id string) (Visit, error)
	ListActiveFacilitatorSessionsByCamp(ctx context.Context, campID string) ([]FacilitatorSession, error)
	ListActiveFacilitatorSessionsByTrack(ctx context.Context, trackID string) ([]FacilitatorSession, error)
	ListActiveTracksByCamp(ctx context.Context, campID string) ([]Track, error)
	ListAdminSessionsByAdmin(ctx context.Context, adminID string) ([]AdminSession, error)
	ListAllBadges(ctx context.Context) ([]Badge, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListBroadcastMessagesByCamp(ctx context.Context) ([]Message, error)
	ListBroadcastReceiptsByMessage(ctx context.Context, messageID string) ([]BroadcastReceipt, error)
	ListCamps(ctx context.Context) ([]Camp, error)
	ListCornersByCamp(ctx context.Context, campID string) ([]Corner, error)
	ListDeviceRegistrationsByCampAndStatus(ctx context.Context, arg ListDeviceRegistrationsByCampAndStatusParams) ([]DeviceRegistration, error)
	ListDirectMessagesByTrack(ctx context.Context, trackID pgtype.Text) ([]Message, error)
	ListGroupsByCamp(ctx context.Context, campID string) ([]Group, error)
	ListPendingDeviceRegistrationsByCamp(ctx context.Context, campID string) ([]DeviceRegistration, error)
	ListTracksByCamp(ctx context.Context, campID string) ([]Track, error)
	ListTracksByCorner(ctx context.Context, cornerID string) ([]Track, error)
	ListVisitsByCamp(ctx context.Context, campID string) ([]ListVisitsByCampRow, error)
	SaveAdminSession(ctx context.Context, arg SaveAdminSessionParams) error
	SaveAuditLog(ctx context.Context, arg SaveAuditLogParams) error
	SaveBadge(ctx context.Context, arg SaveBadgeParams) error
	SaveBroadcastReceipt(ctx context.Context, arg SaveBroadcastReceiptParams) error
	SaveCamp(ctx context.Context, arg SaveCampParams) error
	SaveCorner(ctx context.Context, arg SaveCornerParams) error
	SaveDeviceRegistration(ctx context.Context, arg SaveDeviceRegistrationParams) error
	SaveFacilitatorSession(ctx context.Context, arg SaveFacilitatorSessionParams) error
	SaveGroup(ctx context.Context, arg SaveGroupParams) error
	SaveMessage(ctx context.Context, arg SaveMessageParams) error
	SaveTrack(ctx context.Context, arg SaveTrackParams) error
	SaveVisit(ctx context.Context, arg SaveVisitParams) error
}

var _ Querier = (*Queries)(nil)
