// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAdmins(ctx context.Context) (int64, error)
	CountAdminsByRole(ctx context.Context, role string) (int64, error)
	DeleteAdmin(ctx context.Context, id string) error
	GetAdmin(ctx context.Context, id string) (Admin, error)
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetAdminSession(ctx context.Context, id string) (AdminSession, error)
	GetAdminSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) (AdminSession, error)
	GetAnnouncementReceiptByAnnouncementAndTrack(ctx context.Context, arg GetAnnouncementReceiptByAnnouncementAndTrackParams) (AnnouncementReceipt, error)
	GetBadge(ctx context.Context, id string) (Badge, error)
	GetBadgeByQRPayload(ctx context.Context, qrPayload string) (Badge, error)
	GetCamp(ctx context.Context, id string) (Camp, error)
	GetCampByRegistrationCode(ctx context.Context, registrationCode string) (Camp, error)
	GetCompletedVisitByGroupAndCorner(ctx context.Context, arg GetCompletedVisitByGroupAndCornerParams) (Visit, error)
	GetCorner(ctx context.Context, id string) (Corner, error)
	GetCornerView(ctx context.Context, id string) (GetCornerViewRow, error)
	GetDeviceRegistration(ctx context.Context, id string) (DeviceRegistration, error)
	GetDeviceRegistrationByTokenHash(ctx context.Context, tokenHash string) (DeviceRegistration, error)
	GetFacilitatorSession(ctx context.Context, id string) (FacilitatorSession, error)
	GetFacilitatorSessionByTokenHash(ctx context.Context, tokenHash string) (FacilitatorSession, error)
	GetGroup(ctx context.Context, id string) (Group, error)
	GetGroupByBadge(ctx context.Context, arg GetGroupByBadgeParams) (Group, error)
	GetGroupForUpdate(ctx context.Context, id string) (Group, error)
	GetInProgressVisitByTrack(ctx context.Context, trackID string) (Visit, error)
	GetTrack(ctx context.Context, id string) (Track, error)
	GetVisit(ctx context.Context, id string) (Visit, error)
	IncrementTrackUnreadCount(ctx context.Context, arg IncrementTrackUnreadCountParams) error
	ListActiveFacilitatorSessionsByCamp(ctx context.Context, campID string) ([]FacilitatorSession, error)
	ListActiveFacilitatorSessionsByTrack(ctx context.Context, trackID string) ([]FacilitatorSession, error)
	ListActiveTracksByCamp(ctx context.Context, campID string) ([]Track, error)
	ListAdminSessionsByAdmin(ctx context.Context, adminID string) ([]AdminSession, error)
	ListAllBadges(ctx context.Context) ([]Badge, error)
	ListAnnouncementReceiptViews(ctx context.Context, announcementID string) ([]ListAnnouncementReceiptViewsRow, error)
	ListAnnouncementReceiptsByAnnouncement(ctx context.Context, announcementID string) ([]AnnouncementReceipt, error)
	ListAnnouncementViewsByCampAndTrack(ctx context.Context, arg ListAnnouncementViewsByCampAndTrackParams) ([]ListAnnouncementViewsByCampAndTrackRow, error)
	ListAnnouncementsByCamp(ctx context.Context, campID string) ([]Announcement, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListCamps(ctx context.Context) ([]Camp, error)
	ListCornerViewsByCamp(ctx context.Context, campID string) ([]ListCornerViewsByCampRow, error)
	ListCornersByCamp(ctx context.Context, campID string) ([]Corner, error)
	ListDeviceRegistrationsByCampAndStatus(ctx context.Context, arg ListDeviceRegistrationsByCampAndStatusParams) ([]DeviceRegistration, error)
	ListGroupsByCamp(ctx context.Context, campID string) ([]Group, error)
	ListGroupsByCampForUpdate(ctx context.Context, campID string) ([]Group, error)
	ListInProgressVisitsByCamp(ctx context.Context, campID string) ([]Visit, error)
	ListMessagesByTrack(ctx context.Context, trackID string) ([]Message, error)
	ListMessagesByTrackAfter(ctx context.Context, arg ListMessagesByTrackAfterParams) ([]Message, error)
	ListPendingDeviceRegistrationsByCamp(ctx context.Context, campID string) ([]DeviceRegistration, error)
	ListTracksByCamp(ctx context.Context, campID string) ([]Track, error)
	ListTracksByCorner(ctx context.Context, cornerID string) ([]Track, error)
	ListVisitsByCamp(ctx context.Context, campID string) ([]ListVisitsByCampRow, error)
	ListVisitsByGroup(ctx context.Context, groupID string) ([]Visit, error)
	MarkAllMessagesReadByRecipient(ctx context.Context, arg MarkAllMessagesReadByRecipientParams) error
	PurgeDeletedCorners(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error)
	ResetTrackUnreadCount(ctx context.Context, arg ResetTrackUnreadCountParams) error
	SaveAdmin(ctx context.Context, arg SaveAdminParams) error
	SaveAdminSession(ctx context.Context, arg SaveAdminSessionParams) error
	SaveAnnouncement(ctx context.Context, arg SaveAnnouncementParams) error
	SaveAnnouncementReceipt(ctx context.Context, arg SaveAnnouncementReceiptParams) error
	SaveAuditLog(ctx context.Context, arg SaveAuditLogParams) error
	SaveBadge(ctx context.Context, arg SaveBadgeParams) error
	SaveCamp(ctx context.Context, arg SaveCampParams) error
	SaveCorner(ctx context.Context, arg SaveCornerParams) error
	SaveDeviceRegistration(ctx context.Context, arg SaveDeviceRegistrationParams) error
	SaveFacilitatorSession(ctx context.Context, arg SaveFacilitatorSessionParams) error
	SaveGroup(ctx context.Context, arg SaveGroupParams) error
	SaveMessage(ctx context.Context, arg SaveMessageParams) error
	SaveTrack(ctx context.Context, arg SaveTrackParams) error
	SaveVisit(ctx context.Context, arg SaveVisitParams) error
	SoftDeleteCorner(ctx context.Context, arg SoftDeleteCornerParams) error
}

var _ Querier = (*Queries)(nil)
