// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/events/admin": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자용 실시간 이벤트 스트림",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "F. Events (SSE)"
                ],
                "summary": "Admin SSE Stream",
                "responses": {
                    "200": {
                        "description": "SSE Stream"
                    }
                }
            }
        },
        "/api/v1/events/track/{trackId}": {
            "get": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "트랙 진행자용 실시간 이벤트 스트림",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "F. Events (SSE)"
                ],
                "summary": "Track SSE Stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE Stream"
                    }
                }
            }
        },
        "/audit-logs": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "시스템에서 발생한 중요 행위(인증, 방문, 예외 처리 등)의 감사 로그를 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "G. Audit Logs"
                ],
                "summary": "감사 로그 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "조회 개수",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "오프셋",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.AuditLog"
                            }
                        }
                    }
                }
            }
        },
        "/auth/admin/login": {
            "post": {
                "description": "관리자 ID/비밀번호로 로그인하여 액세스 토큰과 리프레시 토큰을 발급받는다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "관리자 로그인",
                "parameters": [
                    {
                        "description": "로그인 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.AdminLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.AdminLoginResponse"
                        }
                    },
                    "401": {
                        "description": "잘못된 ID 또는 비밀번호",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/admin/logout": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "현재 활성화된 리프레시 토큰(세션)을 취소(Revoke)한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "관리자 로그아웃",
                "responses": {
                    "204": {
                        "description": "로그아웃 성공"
                    },
                    "401": {
                        "description": "권한 없음",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/admin/refresh": {
            "post": {
                "security": [
                    {
                        "AdminRefreshAuth": []
                    }
                ],
                "description": "리프레시 토큰으로 새 액세스 토큰을 발급한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "관리자 액세스 토큰 재발급",
                "responses": {
                    "200": {
                        "description": "새 액세스 토큰 발급",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.AdminRefreshResponse"
                        }
                    },
                    "401": {
                        "description": "권한 없음",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/admin/sessions": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "현재 로그인된 관리자 세션 목록을 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "관리자 세션 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.AdminSession"
                            }
                        }
                    }
                }
            }
        },
        "/auth/admin/sessions/{id}/revoke": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 관리자 세션을 강제 만료 처리한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "관리자 세션 강제 종료",
                "parameters": [
                    {
                        "type": "string",
                        "description": "세션 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "성공적으로 만료 처리됨"
                    }
                }
            }
        },
        "/auth/track/lockout/{deviceId}/release": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자가 PIN 다회 오류로 잠긴 기기를 해제한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "디바이스 락아웃 해제",
                "parameters": [
                    {
                        "type": "string",
                        "description": "기기 ID",
                        "name": "deviceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "성공"
                    }
                }
            }
        },
        "/auth/track/login": {
            "post": {
                "security": [
                    {
                        "TrustedDeviceAuth": []
                    }
                ],
                "description": "신뢰 기기에서 트랙 PIN 으로 로그인하여 트랙 세션 토큰을 발급받는다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "진행자 트랙 PIN 로그인",
                "parameters": [
                    {
                        "description": "6자리 숫자 트랙 PIN",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.TrackLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공 — 트랙 세션 토큰 발급",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.TrackLoginResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 PIN (지연 가능)",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "신뢰 기기 아님 또는 캠프 미시작",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "PIN 잠금(지연) 중",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/track/logout": {
            "post": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "트랙 진행자가 스스로 로그아웃한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "진행자 트랙 로그아웃",
                "responses": {
                    "204": {
                        "description": "성공"
                    }
                }
            }
        },
        "/auth/track/{trackId}/force-logout": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자가 특정 트랙의 진행자 세션을 강제 종료시킨다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "트랙 강제 로그아웃",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "성공"
                    }
                }
            }
        },
        "/badges": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "시스템에 존재하는 전체 배지 목록을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "전체 배지 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Badge"
                            }
                        }
                    }
                }
            }
        },
        "/badges/bulk-generate": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 개수만큼 QR 배지를 대량으로 일괄 발급한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "초기 배지 일괄 생성",
                "parameters": [
                    {
                        "description": "생성할 개수",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.BulkGenerateBadgesRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Badge"
                            }
                        }
                    }
                }
            }
        },
        "/badges/export": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "인쇄소에 넘길 수 있도록 배지의 payload와 숏 코드를 CSV 형식으로 다운로드한다.",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "QR 배지 인쇄용 목록 내보내기",
                "responses": {
                    "200": {
                        "description": "CSV 데이터"
                    }
                }
            }
        },
        "/badges/scan-register": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "QR 코드를 스캔하여 배지를 특정 조에 등록(매핑)한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "배지를 특정 조에 배정 (스캔 기반)",
                "parameters": [
                    {
                        "description": "매핑 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ScanAssignBadgeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Badge"
                        }
                    }
                }
            }
        },
        "/badges/{id}/register": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "수동으로 특정 배지를 조회하여 조에 할당한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "배지를 특정 조에 배정 (수동)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "배지 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "배정할 조 ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.AssignBadgeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Badge"
                        }
                    }
                }
            }
        },
        "/camps": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "전체 캠프 목록을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "캠프 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Camp"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "새로운 코너학습 캠프를 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "새 캠프 생성",
                "parameters": [
                    {
                        "description": "캠프 생성 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.CreateCampRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Camp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/camps/{id}": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 캠프 정보를 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "캠프 상세 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "캠프 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Camp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/camps/{id}/end": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "캠프를 ENDED 상태로 변경한다. 이후 데이터 수정이 불가하다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "캠프 종료",
                "parameters": [
                    {
                        "type": "string",
                        "description": "캠프 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Camp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/camps/{id}/start": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "캠프를 ACTIVE 상태로 변경하고 운영을 시작한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "캠프 시작",
                "parameters": [
                    {
                        "type": "string",
                        "description": "캠프 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Camp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "이미 활성화됨 또는 필수 조건 미충족",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/corners": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 캠프의 모든 코너 목록을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "코너 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "필터링할 캠프 ID",
                        "name": "campId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Corner"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "캠프에 새로운 코너를 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "새 코너 추가",
                "parameters": [
                    {
                        "description": "코너 생성 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.CreateCornerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Corner"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/corners/bulk-update": {
            "put": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "여러 코너의 이름이나 목표 시간을 일괄 수정한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "코너 대량 수정",
                "parameters": [
                    {
                        "description": "수정할 코너 목록",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.BulkUpdateCornersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Corner"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/corners/{cornerId}/tracks": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 코너에 속한 트랙 목록을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "코너별 트랙 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "코너 ID",
                        "name": "cornerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Track"
                            }
                        }
                    }
                }
            }
        },
        "/corners/{id}": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 코너 정보를 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "코너 상세 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "코너 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Corner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "코너를 삭제한다. 단, 방문 기록이 있으면 삭제할 수 없다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "코너 삭제",
                "parameters": [
                    {
                        "type": "string",
                        "description": "코너 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "성공적으로 삭제됨"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "활성화된 캠프이거나 종속 데이터가 존재함",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/device-registrations": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자가 등록되었거나 대기 중인 기기 목록을 확인한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "기기 등록 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.DeviceRegistration"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "기기가 서버에 등록을 요청한다. 이후 관리자의 승인 대기.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "기기 등록 요청 (최초 앱 실행 시)",
                "parameters": [
                    {
                        "description": "등록 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.DeviceRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.DeviceRegistration"
                        }
                    }
                }
            }
        },
        "/device-registrations/me": {
            "get": {
                "description": "미승인(PENDING) 기기가 자신의 승인 상태를 확인하기 위해 호출한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "내 기기 등록 상태 자체 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/device-registrations/{id}/approve": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "PENDING 상태인 기기를 APPROVED로 승인한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "기기 승인",
                "parameters": [
                    {
                        "type": "string",
                        "description": "기기 등록 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.DeviceRegistration"
                        }
                    }
                }
            }
        },
        "/device-registrations/{id}/reject": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "PENDING 상태인 기기를 REJECTED로 거절한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "기기 거절",
                "parameters": [
                    {
                        "type": "string",
                        "description": "기기 등록 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.DeviceRegistration"
                        }
                    }
                }
            }
        },
        "/device-registrations/{id}/revoke": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "APPROVED 기기의 권한을 REVOKED로 박탈한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "A. Auth \u0026 Device Trust"
                ],
                "summary": "기기 신뢰 취소 (폐기/분실)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "기기 등록 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.DeviceRegistration"
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 캠프에 속한 모든 조의 목록과 상태를 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "전체 조 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "캠프 ID 필터",
                        "name": "campId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Group"
                            }
                        }
                    }
                }
            }
        },
        "/groups/{id}": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 조의 현재 위치 및 순회표(Itinerary) 진행 상태를 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "특정 조 상세 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "조 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Group"
                        }
                    }
                }
            }
        },
        "/groups/{id}/visits": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 조의 전체 방문(Visit) 기록과 각 코너의 소요 시간 등을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "조별 방문 기록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "조 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.VisitSummary"
                            }
                        }
                    }
                }
            }
        },
        "/messages/broadcast": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자가 보낸 BROADCAST 메시지들의 목록을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E. Message"
                ],
                "summary": "발송된 공지사항 목록",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Message"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "모든 활성 트랙에 BROADCAST 메시지를 보낸다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E. Message"
                ],
                "summary": "전체 공지 발송",
                "parameters": [
                    {
                        "description": "메시지 내용",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.BroadcastMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Message"
                        }
                    }
                }
            }
        },
        "/messages/broadcast/{id}/read": {
            "post": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "트랙 진행자가 공지사항을 확인(읽음) 처리한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E. Message"
                ],
                "summary": "공지사항 읽음 처리",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메시지 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "성공적으로 읽음 처리됨"
                    }
                }
            }
        },
        "/messages/broadcast/{id}/receipts": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 공지사항에 대해 트랙들의 수신/읽음 상태를 확인한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E. Message"
                ],
                "summary": "공지사항 수신 확인 현황",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메시지 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.BroadcastReceipt"
                            }
                        }
                    }
                }
            }
        },
        "/reports/current": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "현재 활성화된 캠프의 상세 통계(CampReport)를 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "D. Report"
                ],
                "summary": "현재 리포트 전체 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.CampReport"
                        }
                    }
                }
            }
        },
        "/reports/current/export": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "현재 캠프 리포트를 CSV(또는 지정된 포맷)로 다운로드한다.",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "D. Report"
                ],
                "summary": "현재 리포트 데이터 내보내기",
                "responses": {
                    "200": {
                        "description": "CSV 데이터"
                    }
                }
            }
        },
        "/reports/generate": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "캠프가 종료될 때 최종 리포트를 생성하여 저장소에 보관한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "D. Report"
                ],
                "summary": "과거 리포트 생성 및 저장",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.CampReport"
                        }
                    }
                }
            }
        },
        "/reports/live-summary": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "전체 진행 상황(완주율 등)의 핵심 요약 정보를 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "D. Report"
                ],
                "summary": "라이브 서머리 (대시보드 상단)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.CampSummaryStats"
                        }
                    }
                }
            }
        },
        "/tracks": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "전체 트랙 목록을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "트랙 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "캠프 ID 필터",
                        "name": "campId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Track"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 코너에 여러 트랙을 추가 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "트랙 일괄 생성",
                "parameters": [
                    {
                        "description": "생성 정보",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.CreateTracksRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Track"
                            }
                        }
                    }
                }
            }
        },
        "/tracks/bulk-delete": {
            "delete": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "선택한 트랙들을 일괄 삭제한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "트랙 일괄 삭제",
                "parameters": [
                    {
                        "description": "삭제할 트랙 ID 목록",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.BulkDeleteTracksRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "성공적으로 삭제됨"
                    }
                }
            }
        },
        "/tracks/export": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "인쇄를 위해 전체 트랙의 PIN 번호 등을 CSV로 다운로드한다.",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "트랙 인증 정보 전체 내보내기",
                "responses": {
                    "200": {
                        "description": "CSV 데이터"
                    }
                }
            }
        },
        "/tracks/{id}": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "트랙 상세 정보(PIN 등)를 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "트랙 상세 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Track"
                        }
                    }
                }
            }
        },
        "/tracks/{id}/export": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 트랙의 PIN 번호를 PDF 형태로 다운로드한다.",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "단일 트랙 인증 정보 내보내기",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PDF 데이터"
                    }
                }
            }
        },
        "/tracks/{id}/migrate-session": {
            "post": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "트랙이 교체되어 ` + "`" + `track_replaced` + "`" + ` 알림을 받은 기기가 호출한다. 기존 세션 토큰을 Authorization 헤더에 담아 새 세션을 발급받는다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Camp / Corner / Track"
                ],
                "summary": "교체된 트랙의 세션 마이그레이션",
                "parameters": [
                    {
                        "type": "string",
                        "description": "기존 트랙 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.TrackLoginResponse"
                        }
                    },
                    "401": {
                        "description": "권한 없음 또는 세션 만료",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tracks/{id}/regenerate-pin": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "특정 트랙의 PIN 번호를 새로 생성한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "PIN 재발급",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Track"
                        }
                    }
                }
            }
        },
        "/tracks/{id}/replace": {
            "put": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "기기 고장 등으로 트랙 세션을 초기화하거나 새 기기로 교체할 수 있도록 처리한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B. Resource Management (Admin)"
                ],
                "summary": "트랙 교체 (비상용)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Track"
                        }
                    }
                }
            }
        },
        "/tracks/{trackId}/messages": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자 또는 트랙 진행자가 해당 트랙과 관련된 DIRECT 메시지 내역을 조회한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E. Message"
                ],
                "summary": "트랙별 메시지 내역 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infrastructure_web.Message"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "관리자가 특정 트랙에, 또는 특정 트랙이 관리자에게 DIRECT 메시지를 발송한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E. Message"
                ],
                "summary": "다이렉트 메시지 발송",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "메시지 내용",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.DirectMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.Message"
                        }
                    }
                }
            }
        },
        "/tracks/{trackId}/visits/current": {
            "get": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "스캐너 앱이 크래시되거나 새로고침 되었을 때, 현재 트랙에서 진행 중인 방문이 있는지 확인.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "C. Visit (Scan Flow)"
                ],
                "summary": "현재 진행 중인 방문 상태 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.VisitSummary"
                        }
                    },
                    "404": {
                        "description": "진행 중인 방문 없음"
                    }
                }
            }
        },
        "/tracks/{trackId}/visits/current/end": {
            "post": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "진행 중인 방문을 종료 처리한다. (화면의 종료 확인 2회 탭)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "C. Visit (Scan Flow)"
                ],
                "summary": "현재 방문 종료 (조 퇴장)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.VisitSummary"
                        }
                    },
                    "409": {
                        "description": "TRACK_NOT_BUSY 등",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tracks/{trackId}/visits/start": {
            "post": {
                "security": [
                    {
                        "TrackAuth": []
                    }
                ],
                "description": "진행자가 조의 입장을 처리한다. QR 스캔 또는 수동 처리.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "C. Visit (Scan Flow)"
                ],
                "summary": "방문 시작 (조 입장)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "트랙 ID",
                        "name": "trackId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "입장 방식 및 페이로드",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.VisitStartRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.VisitSummary"
                        }
                    },
                    "409": {
                        "description": "TRACK_BUSY, DUPLICATE_VISIT 등",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_web.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infrastructure_web.AdminLoginRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.AdminLoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresInSeconds": {
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.AdminRefreshResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresInSeconds": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.AdminSession": {
            "type": "object",
            "properties": {
                "adminId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "deviceInfo": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "lastUsedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "internal_infrastructure_web.AssignBadgeRequest": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.AuditLog": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "actor": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "occurredAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "success": {
                    "type": "boolean"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.Badge": {
            "type": "object",
            "properties": {
                "assignedGroupId": {
                    "type": "string",
                    "format": "uuid"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "qrPayload": {
                    "type": "string"
                },
                "shortId": {
                    "type": "string",
                    "example": "B-0042"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "UNASSIGNED",
                        "ASSIGNED"
                    ]
                }
            }
        },
        "internal_infrastructure_web.BottleneckRanking": {
            "type": "object",
            "properties": {
                "avgDeviationSeconds": {
                    "type": "number"
                },
                "cornerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "cornerName": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.BroadcastMessageRequest": {
            "type": "object",
            "properties": {
                "campId": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.BroadcastReceipt": {
            "type": "object",
            "properties": {
                "cornerName": {
                    "type": "string"
                },
                "isRead": {
                    "type": "boolean"
                },
                "readAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "trackId": {
                    "type": "string",
                    "format": "uuid"
                },
                "trackNo": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.BulkDeleteTracksRequest": {
            "type": "object",
            "properties": {
                "trackIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_infrastructure_web.BulkGenerateBadgesRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.BulkUpdateCornersRequest": {
            "type": "object",
            "properties": {
                "corners": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "targetMinutes": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "internal_infrastructure_web.Camp": {
            "type": "object",
            "properties": {
                "bottleneckMinSamples": {
                    "type": "integer",
                    "example": 3
                },
                "bottleneckRatioPct": {
                    "type": "integer",
                    "example": 20
                },
                "endAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string",
                    "example": "2026 여름 코너학습"
                },
                "startAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "ACTIVE",
                        "ENDED"
                    ]
                }
            }
        },
        "internal_infrastructure_web.CampReport": {
            "type": "object",
            "properties": {
                "campId": {
                    "type": "string",
                    "format": "uuid"
                },
                "cornerStats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.CornerStats"
                    }
                },
                "generatedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "groupStats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.GroupStats"
                    }
                },
                "operationalStats": {
                    "$ref": "#/definitions/internal_infrastructure_web.OperationalStats"
                },
                "summary": {
                    "$ref": "#/definitions/internal_infrastructure_web.CampSummaryStats"
                },
                "timeline": {
                    "$ref": "#/definitions/internal_infrastructure_web.TimelineStats"
                },
                "trackStats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.TrackStats"
                    }
                }
            }
        },
        "internal_infrastructure_web.CampSummaryStats": {
            "type": "object",
            "properties": {
                "avgDeviationSeconds": {
                    "type": "number"
                },
                "bottleneckRanking": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.BottleneckRanking"
                    }
                },
                "completionRate": {
                    "type": "number"
                },
                "exceptionApprovalCount": {
                    "type": "integer"
                },
                "finishedGroupCount": {
                    "type": "integer"
                },
                "manualVisitRatio": {
                    "type": "number"
                },
                "programDurationSeconds": {
                    "type": "integer"
                },
                "ruleOverrideCount": {
                    "type": "integer"
                },
                "totalGroups": {
                    "type": "integer"
                },
                "totalVisits": {
                    "type": "integer"
                },
                "trackOperationCount": {
                    "type": "integer"
                },
                "visitCompletionRate": {
                    "type": "number"
                }
            }
        },
        "internal_infrastructure_web.Corner": {
            "type": "object",
            "properties": {
                "activeTracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.TrackSummary"
                    }
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "isBottleneck": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "코너 1"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "INACTIVE",
                        "IDLE",
                        "BUSY"
                    ]
                },
                "targetMinutes": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "internal_infrastructure_web.CornerProgress": {
            "type": "object",
            "properties": {
                "cornerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "cornerName": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "NOT_VISITED",
                        "IN_PROGRESS",
                        "COMPLETED"
                    ]
                }
            }
        },
        "internal_infrastructure_web.CornerStats": {
            "type": "object",
            "properties": {
                "completedVisitCount": {
                    "type": "integer"
                },
                "cornerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "cornerName": {
                    "type": "string"
                },
                "unvisitedGroups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.UnvisitedGroup"
                    }
                }
            }
        },
        "internal_infrastructure_web.CreateCampRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.CreateCornerRequest": {
            "type": "object",
            "properties": {
                "campId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "targetMinutes": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.CreateTracksRequest": {
            "type": "object",
            "properties": {
                "campId": {
                    "type": "string"
                },
                "cornerId": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.DeviceRegistration": {
            "type": "object",
            "properties": {
                "approvedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "deviceName": {
                    "type": "string",
                    "example": "iPad Pro #3"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "APPROVED",
                        "REJECTED",
                        "REVOKED"
                    ]
                }
            }
        },
        "internal_infrastructure_web.DeviceRegistrationRequest": {
            "type": "object",
            "properties": {
                "campId": {
                    "description": "Using campId because RequestRegistration expects a campID",
                    "type": "string"
                },
                "deviceName": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "ADMIN",
                        "FACILITATOR"
                    ]
                }
            }
        },
        "internal_infrastructure_web.DirectMessageRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_REQUEST"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string",
                    "example": "잘못된 요청입니다."
                }
            }
        },
        "internal_infrastructure_web.Group": {
            "type": "object",
            "properties": {
                "badgeId": {
                    "type": "string",
                    "format": "uuid"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "isFinished": {
                    "type": "boolean"
                },
                "itinerary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_web.CornerProgress"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "1조"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "IDLE_MOVING",
                        "AT_CORNER",
                        "FINISHED"
                    ]
                }
            }
        },
        "internal_infrastructure_web.GroupStats": {
            "type": "object",
            "properties": {
                "completedCount": {
                    "type": "integer"
                },
                "groupId": {
                    "type": "string",
                    "format": "uuid"
                },
                "groupName": {
                    "type": "string"
                },
                "totalDurationSeconds": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.Message": {
            "type": "object",
            "properties": {
                "channelType": {
                    "type": "string",
                    "enum": [
                        "BROADCAST",
                        "DIRECT"
                    ]
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "isRead": {
                    "type": "boolean"
                },
                "readAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "senderRole": {
                    "type": "string",
                    "enum": [
                        "ADMIN",
                        "TRACK"
                    ]
                },
                "sentAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "trackId": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "internal_infrastructure_web.OperationalStats": {
            "type": "object"
        },
        "internal_infrastructure_web.ScanAssignBadgeRequest": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string"
                },
                "qrPayload": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.TimelineStats": {
            "type": "object"
        },
        "internal_infrastructure_web.Track": {
            "type": "object",
            "properties": {
                "cornerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "currentVisit": {
                    "$ref": "#/definitions/internal_infrastructure_web.VisitSummary"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "operationalStatus": {
                    "type": "string",
                    "enum": [
                        "IDLE",
                        "BUSY"
                    ]
                },
                "pin": {
                    "type": "string",
                    "example": "482910"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "DELETED"
                    ]
                },
                "trackNo": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.TrackLoginRequest": {
            "type": "object",
            "properties": {
                "pin": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.TrackLoginResponse": {
            "type": "object",
            "properties": {
                "corner": {
                    "$ref": "#/definitions/internal_infrastructure_web.Corner"
                },
                "track": {
                    "$ref": "#/definitions/internal_infrastructure_web.Track"
                },
                "trackToken": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.TrackStats": {
            "type": "object",
            "properties": {
                "avgDeviationSeconds": {
                    "type": "integer"
                },
                "handledVisitCount": {
                    "type": "integer"
                },
                "manualVisitRatio": {
                    "type": "number"
                },
                "trackId": {
                    "type": "string",
                    "format": "uuid"
                },
                "trackNo": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.TrackSummary": {
            "type": "object",
            "properties": {
                "cornerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "operationalStatus": {
                    "type": "string",
                    "enum": [
                        "IDLE",
                        "BUSY"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ACTIVE",
                        "DELETED"
                    ]
                },
                "trackNo": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_web.UnvisitedGroup": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string",
                    "format": "uuid"
                },
                "groupName": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.VisitStartRequest": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string"
                },
                "method": {
                    "type": "string",
                    "enum": [
                        "MANUAL"
                    ]
                },
                "qrToken": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_web.VisitSummary": {
            "type": "object",
            "properties": {
                "cornerId": {
                    "type": "string",
                    "format": "uuid"
                },
                "deviationSeconds": {
                    "type": "integer"
                },
                "durationSeconds": {
                    "type": "integer"
                },
                "endedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "groupId": {
                    "type": "string",
                    "format": "uuid"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "inputMethod": {
                    "type": "string",
                    "enum": [
                        "QR_SCAN",
                        "MANUAL"
                    ]
                },
                "startedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "IN_PROGRESS",
                        "COMPLETED"
                    ]
                },
                "trackId": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
